# Generated by Django 3.2 on 2022-07-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flavor',
        ),
    ]
