# Generated by Django 3.2 on 2022-07-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_f', models.CharField(blank='True', max_length=30, null='True')),
                ('description_f', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Flavors',
            },
        ),
    ]
