# Generated by Django 3.2 on 2022-07-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_flavor_title_f'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_f', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Title Page',
            },
        ),
    ]
