# Generated by Django 3.2 on 2022-07-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutImage',
        ),
    ]
