# Generated by Django 3.2 on 2022-07-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_aboutimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_f', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'History',
            },
        ),
    ]
