# Generated by Django 3.2 on 2022-07-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons_field', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Icons',
            },
        ),
    ]
