# Generated by Django 3.2 on 2022-07-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220728_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
